server:
  port: 9002 #端口
spring:
  application:
    name: activemq-consumer # 服务名称

# springboot与activemq整合配置
  activemq:
    broker-url: failover:(tcp://192.168.66.133:61616,tcp://192.168.66.133:61617,tcp://192.168.66.133:616168) # 连接地址
    user: admin # activemq用户名
    password: admin # activemq密码
    packages:
      trust-all: true

# 指定发送模式 （点对点 false ， 发布订阅 true）
  jms:
    pub-sub-domain: false

activemq:
  name: springboot_queue